POST http://localhost:8080/event/create-event
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzM1MTA2ODcsInVzZXJJZCI6MiwidXNlcm5hbWUiOiJsb2wifQ.XaAvkioVXpIeAD6VirqKkf-sL1b64ijB5nzempcpRZs 

{
    "Name": "las",
    "Description": "mas",
    "Location": "ras"
}